version: '3'
services:
  database:
    image: mysql:8.0
    container_name: mysql_hotels
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pas
      MYSQL_DATABASE: hotels
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: